import styled from "../../styled";

const StyledSelectItem = styled.input`
  background-color: rgb(255, 255, 255);
  background-image: none;
  border-bottom-color: rgb(166, 201, 230);
  border-bottom-left-radius: 4px;
  border-bottom-right-radius: 4px;
  border-bottom-style: solid;
  border-bottom-width: 1px;
  border-image-outset: 0px;
  border-image-repeat: stretch;
  border-image-slice: 100%;
  border-image-source: none;
  border-image-width: 1;
  border-left-color: rgb(166, 201, 230);
  border-left-style: solid;
  border-left-width: 1px;
  border-right-color: rgb(166, 201, 230);
  border-right-style: solid;
  border-right-width: 1px;
  border-top-color: rgb(166, 201, 230);
  border-top-left-radius: 4px;
  border-top-right-radius: 4px;
  border-top-style: solid;
  border-top-width: 1px;
  box-sizing: border-box;
  color: rgba(0, 0, 0, 0.65);
  cursor: text;
  display: inline-block;
  font-size: 14px;
  font-stretch: 100%;
  font-style: normal;
  font-variant-caps: normal;
  font-variant-east-asian: normal;
  font-variant-ligatures: normal;
  font-variant-numeric: tabular-nums;
  font-weight: 400;
  height: 32px;
  letter-spacing: normal;
  line-height: 21px;
  list-style-image: none;
  list-style-position: outside;
  list-style-type: none;
  margin-bottom: 0px;
  margin-left: 0px;
  margin-right: 0px;
  margin-top: 0px;
  overflow-x: visible;
  overflow-y: visible;
  padding-bottom: 4px;
  padding-left: 11px;
  padding-right: 11px;
  padding-top: 4px;
  position: relative;
  text-align: start;
  text-indent: 0px;
  text-rendering: auto;
  text-shadow: none;
  text-size-adjust: 100%;
  text-transform: none;
  touch-action: manipulation;
  transition-delay: 0s;
  transition-duration: 0.3s;
  transition-property: all;
  transition-timing-function: ease;
  width: 235.25px;
  word-spacing: 0px;
  writing-mode: horizontal-tb;
  -webkit-appearance: none;
  -webkit-rtl-ordering: logical;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
`;
export const SelectItem = StyledSelectItem;